version: '3.8'

services:
  streamlit:
    image: call518/perplexis:1.0.1
    environment:
      - PERPLEXIS_BRANCH=main
      - OLLAMA_BASE_URL=http://localhost:11434
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - OPENAI_API_KEY=
      - PINECONE_API_KEY=
      - LANGCHAIN_API_KEY=
    depends_on:
      - pgvector
    ports:
      - "18501:8501"

  pgvector:
    image: call518/pgvector:pg16-1.0.0
    environment:
      - POSTGRES_USER=perplexis
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=perplexis
    volumes:
      - pgvector-pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"

volumes:
  pgvector-pgdata: