version: '3.8'

services:
  streamlit:
    image: call518/perplexis:1.0.3
    environment:
      # - PERPLEXIS_BRANCH=main
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - OPENAI_API_KEY=
      - PINECONE_API_KEY=
      - LANGCHAIN_API_KEY=
      - PGVECTOR_HOST = localhost
      - PGVECTOR_PORT = 5432
      - PGVECTOR_USER = perplexis
      - PGVECTOR_PASS = changeme
    volumes:
      - .:/Perplexis
    ports:
      - "8501:8501"
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgvector:
    image: call518/pgvector:pg16-1.0.0
    environment:
      - POSTGRES_USER=perplexis
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=perplexis
    volumes:
      - pgvector-pgdata:/var/lib/postgresql/data
    network_mode: "service:streamlit"
    depends_on:
      - streamlit

volumes:
  pgvector-pgdata: