[KEYS]
### (Mandatory)
OLLAMA_BASE_URL = "{your ollama api server base url}"
OPENAI_BASE_URL = "https://api.openai.com/v1"
OPENAI_API_KEY = "{your openai api key}"
PINECONE_API_KEY = "{your pinecone api key}"

### (Optional)
LANGCHAIN_API_KEY = "{your langchain api key}"
